ignored_colors = [
    #000000, # filter black, DO NOT USE "#"!!!
]
allowed_colors = [
    #000000, # allow black, DO NOT USE "#"!!!
    "FF4500",
    "FFA800",
    "FFD635",
    "00A368",
    "7EED56",
    "2450A4",
    "3690EA",
    "51E9F4",
    "811E9F",
    "B44AC0",
    "FF99AA",
    "9C6926",
    "000000",
    "898D90",
    "D4D7D9",
    "FFFFFF"
]
width = 2000
height = 1500
add-x = 1000
add-y = 1000

default_prio = 120 # priority: higher number = higher chance of being placed


# example:
# [[structure]]
# name = "flagge-ost"
# file = "flagge-ost.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127
# overlay_only = false

[[structure]]
name = "flag-top"
file = "flag-top.png"
startx = -1000
starty = -1000
priority = 100

[[structure]]
name = "flag-top-mid"
file = "flag-top.png"
startx = -1000
starty = -610
priority = 100

[[structure]]
name = "orig-flag"
file = "flag-mid.png"
startx = -1000
starty = -450
priority = 100
